name: Update members

on:
  workflow_dispatch:
    # Uncomment to schedule builds
    #  schedule: 
    #- cron:  '0 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout landscape
        uses: actions/checkout@v2
        with:
          path: main
      - name: Checkout landscape-tools
        uses: actions/checkout@v2
        with:
          repository: jmertic/landscape-tools
          path: landscape-tools
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r landscape-tools/requirements.txt
      - name: Run build
        working-directory: ./main
        run: |
          ../landscape-tools/landscapemembers.py
      - name: Save missing.csv file
        uses: actions/upload-artifact@v2
        with:
          name: missing-members 
          path: ./main/missing.csv
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          branch-suffix: timestamp
          path: ./main
          title: Member update
          labels: automatedupdate
          commit-message: Member update
