name: "Set Issue Label on successful build"
on:
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      pull-requests: write
    steps:
      - uses: Amwam/issue-comment-action@v1.3.1
        if: ${{ github.event.issue.pull_request && contains(github.event.issue.labels.*.name, 'automatedupdate') }}
        with:
          keywords: '["Deploy preview for *lfn-landscape* ready"]'
          labels: '["automerge"]'
          github-token: "${{ secrets.GITHUB_TOKEN }}"
