name: Update members

on:
  workflow_dispatch:
  schedule:
    # Run a build everyday at 10AM PST
    - cron: '0 17 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      pull-requests: write
    steps:
      - name: Checkout Landscape
        uses: actions/checkout@v3
        with:
          path: landscape
      - name: Checkout landscape-tools
        uses: actions/checkout@v3
        with:
          repository: jmertic/landscape-tools
          path: landscape-tools
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r landscape-tools/requirements.txt
      - name: Run build
        working-directory: ./landscape
        run: |
          ../landscape-tools/landscapemembers.py
      - name: Save missing.csv file
        uses: actions/upload-artifact@v3
        with:
          name: missing-members
          path: ./landscape/missing.csv
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch-suffix: timestamp
          path: ./landscape
          title: Update members
          labels: automatedupdate
          commit-message: Update members
